Create poller
smartcontractkit/chainlink-common pull request #474
Opened 2024-04-17 23:22 UTC by DylanTinianov

2024-04-18 11:28 UTC, dhaidashenko requested changes

2024-04-18 11:28 UTC, dhaidashenko commented on pkg/utils/poller/poller.go
> +	subscribers []*mailbox.Mailbox[T]
We should not use mailbox as it drops old messages, if we exceed queue capacity. Each instance of the Poller should be used by single subscriber. If subscriber does not read msg from the channel, it's fine to block the polling goroutine

2024-04-18 11:28 UTC, dhaidashenko commented on pkg/utils/poller/poller.go
> +func NewPoller[T any](pollingInterval time.Duration, pollingFunc func() (T, error), logger logger.Logger) *Poller[T] {
We'll use this component to implement methods with [following signatures](https://github.com/smartcontractkit/chainlink/blob/89abd726b6c3f29a84e0fc5d230a1324f622755b/core/chains/evm/client/rpc_client.go#L344)
`Subscribe(ctx context.Context, channel chan<- *evmtypes.Head, args ...interface{}) (commontypes.Subscription, error)`

We should try to simplify this process as much as possible. For instance we should right away return type that implements [Subscription interface.](https://github.com/smartcontractkit/chainlink/blob/578cc6b73acf323740a73abfd8e96b2ba444462b/common/types/subscription.go#L8)

2024-04-22 16:41 UTC, closed without merging

2024-04-22 16:41 UTC, DylanTinianov commented
Moving to `chainlink/common`