Revert "CCIP-2791 Fixes to the snoozed roots - more generic way of passing finality with TxMeta "
smartcontractkit/chainlink-common pull request #668
Opened 2024-07-19 13:39 UTC by 0xnogo

Reverts smartcontractkit/chainlink-common#650

2024-07-20 12:57 UTC, patrickhuie19 reviewed
IMHO it will be helpful to have the follow-up PRs ready to go so that this can be handled in short order without too much disruption to anyone else who is working off the heads of common, ccip, or chainlink. 

> The revert is the only option in order to bump chainlink-common in ccip repo. After that, we could revert this revert which will allow the merge of the PR https://github.com/smartcontractkit/ccip/pull/1198.

To clarify the order of operations:
1. Merge this PR (common 668)
2. Merge https://github.com/smartcontractkit/ccip/pull/1215
3. Merge the revert of common 668
4. https://github.com/smartcontractkit/ccip/pull/1198

?

2024-07-22 10:55 UTC, patrickhuie19 approved these changes

2024-07-24 07:58 UTC, makramkd approved these changes

2024-07-24 09:12 UTC, mateusz-sekara requested changes
Please don't revert that, change in ccip repo is one-liner and it's already reflected in the other PR in ccip repo that was not merged yet

2024-07-29 17:30 UTC, closed without merging