Handle nils in values proto conversion functions
smartcontractkit/chainlink-common pull request #676
Opened 2024-07-29 12:45 UTC by cedric-cordenier

2024-07-29 16:24 UTC, krehermann requested changes
please add a ticket link to the PR and up date the existing ticket with the explicit scope of the findings.

it's not possible to understand if this changes addresses the findings ATM

2024-07-29 16:49 UTC, jmank88 submitted a review, later dismissed

2024-07-30 13:54 UTC, krehermann submitted a review, later dismissed

2024-07-30 17:05 UTC, krehermann approved these changes

2024-07-30 17:20 UTC, jmank88 approved these changes

2024-07-30 17:31 UTC, merged