feat(tooling-apis): adds job-distributor API
smartcontractkit/chainlink-common pull request #733
Opened 2024-08-26 16:47 UTC by MStreet3

* Adds the protobuf definitions for `job-distributor` and `orchestrator` services
* Adds generated Go SDKs for services
* Adds code generation tasks

2024-08-28 17:38 UTC, AnieeG approved these changes

2024-08-28 19:35 UTC, krehermann approved these changes

2024-08-28 20:13 UTC, patrickhuie19 commented on tooling-apis/job-distributor/job/job.proto
> +service JobService {
What are the lifecycles of Jobs and Job proposals? Should they have full CRUDL handler implementations?

2024-08-28 20:15 UTC, patrickhuie19 commented on tooling-apis/job-distributor/node/node.proto
> +  rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse) {}
Is there a case where "de-register" a node would be useful?

2024-08-28 20:52 UTC, jmank88 commented
How many modules do we expect there to be?

Could some of them be combined? e.g. is it important for orchestrator/node and orchestrator/proposer to be completely independent modules? Could we even have one `sdk/go` module?

And for the .proto definitions. I personally like them alongside or even inside the package with the generated files. I think some version of that would simplify the source tree a bit.

2024-08-28 20:52 UTC, jmank88 requested changes
I think we need to be very careful before creating this many modules

2024-08-30 18:04 UTC, MStreet3 commented
Closed following discussion.

2024-08-30 18:04 UTC, closed without merging