update head data to be optional
smartcontractkit/chainlink-common pull request #898
Opened 2024-10-29 11:25 UTC by ettec

The underlying head tracker returns a pointer to head data, this updates the GetLatestValueWithHeadData to do the same.

2024-10-29 12:19 UTC, ilija42 submitted a review, later dismissed

2024-10-29 13:38 UTC, ilija42 requested changes
Look at `TestGetLatestValue` in `pkg/loop/internal/relayer/pluginprovider/contractreader/contract_reader_test.go`, this method should have similar tests

2024-10-30 10:56 UTC, ilija42 approved these changes

2024-10-30 10:57 UTC, ilija42 requested changes
there is a test failure

2025-03-26 10:16 UTC, ettec commented
Dead - GetLatestValueWithHeadData added as part of another PR.

2025-03-26 10:16 UTC, closed without merging